name: client
description: A beautiful weather app
publish_to: 'none'
version: 1.0.0+1
authors:
  - Mehrdad Shokri
repository: https

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.5
  dio: ^4.0.6
  get_it: ^7.2.0
  enum_to_string: ^2.0.1
  shared_preferences: ^2.0.15
  logging: ^1.0.2
  flutter_platform_widgets: ^2.0.0
  lottie: ^1.4.0
  flutter_dotenv: ^5.0.2
  permission_handler: ^10.0.0
  connectivity_plus: ^2.3.6
  internet_connection_checker: ^0.0.1+4
  geolocator: ^9.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.3

flutter:
  uses-material-design: true
  generate: true