name: client
description: A beautiful weather app
publish_to: 'none'
version: 1.0.0+1
repository: https://github.com/mehrdad-shokri/feather
issue_tracker: https://github.com/mehrdad-shokri/feather/issues
documentation: https://github.com/mehrdad-shokri/feather
homepage: https://github.com/mehrdad-shokri/feather/issues

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.5
  dio: ^4.0.6
  get_it: ^7.2.0
  enum_to_string: ^2.0.1
  shared_preferences: ^2.0.15
  logging: ^1.0.2
  flutter_platform_widgets: ^2.0.0
  lottie: ^1.4.0
  flutter_dotenv: ^5.0.2
  connectivity_plus: ^2.3.6
  internet_connection_checker: ^0.0.1+4
  geolocator: ^9.0.1
  crypto: ^3.0.2
  flutter_svg: ^1.1.3
  loading_animation_widget: ^1.2.0+2
  fluttertoast: ^8.0.9
  country_icons: ^2.0.2
  dio_logging_interceptor: ^1.0.1
  text_scroll: ^0.1.0
  intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.7
flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - .env.test
    - assets/images/
    - assets/lottie/
    - assets/svg/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
    - family: Feather
      fonts:
        - asset: assets/fonts/Feather/Feather.ttf
