/// Flutter icons Feather
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Feather
///      fonts:
///       - asset: fonts/Feather.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Feather {
  Feather._();

  static const _kFontFam = 'Feather';
  static const String? _kFontPkg = null;

  static const IconData sliders_h = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bullseye_1 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fahrenheit = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData celcius = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windy = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain_inv = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drizzle_inv = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drizzle = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_flash_inv = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_inv = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_flash = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_moon_inv = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_sun_inv = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fog = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon_inv = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun_inv = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fog_cloud = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clouds_flash_alt = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fog_sun = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fog_moon = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_moon = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_sun = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snowflake = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clouds = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hail = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clouds_flash = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wind = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mist = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eclipse = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow_heavy = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow_alt = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windy_rain = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windy_inv = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sunrise = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windy_rain_inv = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow_inv = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow_heavy_inv = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hail_inv = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clouds_inv = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clouds_flash_inv = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData na = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temperature = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_flash_alt = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain_1 = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drizzle_1 = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_wind = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wind_1 = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_sun_1 = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData waves = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData waves_outline = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash_outline = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_flash_1 = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow_1 = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temperatire = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_outline = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_alt_outline = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_alt = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun_filled = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun_1 = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_1 = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon_1 = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin_drop = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_pin_circle = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xf031, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sliders = IconData(0xf1de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_pin = IconData(0xf276, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
